/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import bus.DiemBUS;
import bus.LopBUS;
import bus.MonHocBUS;
import bus.SinhVienBUS;
import dto.Diem;
import dto.Lop;
import dto.MonHoc;
import dto.SinhVien;

import java.awt.*;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nguye
 */
public class DiemPanel extends javax.swing.JPanel {

    // KHAI BÁO CÁC BUS
    private LopBUS lopBUS = new LopBUS();
    private MonHocBUS monHocBUS = new MonHocBUS();
    private SinhVienBUS svBUS = new SinhVienBUS();
    private DiemBUS diemBUS = new DiemBUS();

    private DefaultTableModel tblModel;

    /**
     * Creates new form DiemPanel
     */
    public DiemPanel() {
        initComponents();
        initTable();
        loadComboBoxLop();    // Tải danh sách Lớp
        loadComboBoxMonHoc(); // Tải danh sách Môn học
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabelTitle = new javax.swing.JLabel();
        jPanelInput = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cboLop = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cboMonHoc = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtMaSV = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtDiem = new javax.swing.JTextField();
        btnCapNhat = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        btnXemDS = new javax.swing.JButton();
        jPanelTable = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDiem = new javax.swing.JTable();

        jLabelTitle.setFont(new java.awt.Font("Segou UI", Font.BOLD, 24)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(51, 102, 255));
        jLabelTitle.setText("Quản lý điểm sinh viên");

        jPanelInput.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông Tin & Nhập Điểm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        jLabel1.setText("Chọn Lớp:");
        jLabel2.setText("Chọn Môn:");
        jLabel3.setText("Mã SV:");

        txtMaSV.setEditable(false);
        txtMaSV.setBackground(new java.awt.Color(240, 240, 240));

        jLabel4.setText("Họ Tên:");

        txtHoTen.setEditable(false);
        txtHoTen.setBackground(new java.awt.Color(240, 240, 240));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Điểm Số:");

        btnCapNhat.setText("Cập nhật điểm");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        btnLamMoi.setText("Làm mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        btnXemDS.setText("Xem danh sách");
        btnXemDS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemDSActionPerformed(evt);
            }
        });

        // CẤU HÌNH LAYOUT CHO PANEL INPUT
        javax.swing.GroupLayout jPanelInputLayout = new javax.swing.GroupLayout(jPanelInput);
        jPanelInput.setLayout(jPanelInputLayout);

        jPanelInputLayout.setHorizontalGroup(
                jPanelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelInputLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                // Cột Label 1
                                .addGroup(jPanelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                // Cột Input 1 (Cố định 200px)
                                .addGroup(jPanelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cboLop, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtMaSV, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtDiem, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(50, 50, 50)
                                // Cột Label 2
                                .addGroup(jPanelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                // Cột Input 2 (Cố định 200px)
                                .addGroup(jPanelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cboMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(127, Short.MAX_VALUE))
                        // Hàng nút bấm căn giữa
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInputLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnXemDS)
                                .addGap(18, 18, 18)
                                .addComponent(btnCapNhat)
                                .addGap(18, 18, 18)
                                .addComponent(btnLamMoi)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelInputLayout.setVerticalGroup(
                jPanelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelInputLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(jPanelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(cboLop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2)
                                        .addComponent(cboMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(txtMaSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4)
                                        .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5)
                                        .addComponent(txtDiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(25, 25, 25)
                                .addGroup(jPanelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnCapNhat)
                                        .addComponent(btnLamMoi)
                                        .addComponent(btnXemDS))
                                .addContainerGap(15, Short.MAX_VALUE))
        );

        // CẤU HÌNH PANEL CHỨA BẢNG
        jPanelTable.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bảng Điểm Lớp", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        tblDiem.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {},
                new String [] {
                        "Mã SV", "Họ Tên", "Điểm Thi"
                }
        ));
        tblDiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDiemMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDiem);

        javax.swing.GroupLayout jPanelTableLayout = new javax.swing.GroupLayout(jPanelTable);
        jPanelTable.setLayout(jPanelTableLayout);
        jPanelTableLayout.setHorizontalGroup(
                jPanelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1) // Tràn viền
        );
        jPanelTableLayout.setVerticalGroup(
                jPanelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE) // Tràn viền dọc
        );

        // CẤU HÌNH LAYOUT CHÍNH
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPanelInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE) // Giãn ngang tối đa
                                        .addComponent(jPanelTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE) // Giãn ngang tối đa
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabelTitle)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabelTitle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanelInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE) // Giữ chiều cao
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanelTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE) // Giãn hết phần còn lại
                                .addContainerGap())
        );
    }// </editor-fold>

    // SỰ KIỆN NÚT BẤM

    private void btnXemDSActionPerformed(java.awt.event.ActionEvent evt) {
        loadData();
    }

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            if (txtMaSV.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Vui lòng chọn sinh viên từ bảng!");
                return;
            }
            if (txtDiem.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Chưa nhập điểm!");
                return;
            }

            Diem d = new Diem();
            d.setMaSV(txtMaSV.getText());

            MonHoc selectedMon = (MonHoc) cboMonHoc.getSelectedItem();
            if (selectedMon != null) d.setMaMon(selectedMon.getMaMon());

            d.setDiem(Double.parseDouble(txtDiem.getText()));

            String msg = diemBUS.saveDiem(d);
            JOptionPane.showMessageDialog(this, msg);

            if (msg.contains("thành công")) {
                loadData();
                txtDiem.setText("");
                txtDiem.requestFocus();
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Điểm phải là số (0-10)!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi: " + e.getMessage());
        }
    }

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {
        txtMaSV.setText("");
        txtHoTen.setText("");
        txtDiem.setText("");
        tblDiem.clearSelection();
    }

    private void tblDiemMouseClicked(java.awt.event.MouseEvent evt) {
        int row = tblDiem.getSelectedRow();
        if (row >= 0) {
            txtMaSV.setText(tblDiem.getValueAt(row, 0).toString());
            txtHoTen.setText(tblDiem.getValueAt(row, 1).toString());

            Object diemVal = tblDiem.getValueAt(row, 2);
            txtDiem.setText(diemVal != null && !diemVal.toString().isEmpty() ? diemVal.toString() : "");
        }
    }

    // CÁC HÀM HỖ TRỢ

    private void initTable() {
        tblModel = new DefaultTableModel();
        tblModel.setColumnIdentifiers(new String[]{"Mã SV", "Họ Tên", "Điểm Thi"});
        tblDiem.setModel(tblModel);
    }

    private void loadComboBoxLop() {
        try {
            List<Lop> list = lopBUS.getAll();
            DefaultComboBoxModel<Lop> model = new DefaultComboBoxModel<>();
            for (Lop l : list) model.addElement(l);
            cboLop.setModel(model);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void loadComboBoxMonHoc() {
        try {
            List<MonHoc> list = monHocBUS.getAll();
            DefaultComboBoxModel<MonHoc> model = new DefaultComboBoxModel<>();
            for (MonHoc mh : list) model.addElement(mh);
            cboMonHoc.setModel(model);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void loadData() {
        Lop selectedLop = (Lop) cboLop.getSelectedItem();
        MonHoc selectedMon = (MonHoc) cboMonHoc.getSelectedItem();

        if (selectedLop == null || selectedMon == null) return;

        tblModel.setRowCount(0);
        try {
            List<SinhVien> listSV = svBUS.getSinhVienByLop(selectedLop.getMaLop());

            for (SinhVien sv : listSV) {
                double diemSo = -1;

                List<Diem> listDiem = diemBUS.getBangDiem(sv.getMaSV());
                for (Diem d : listDiem) {
                    if (d.getMaMon().equals(selectedMon.getMaMon())) {
                        diemSo = d.getDiem();
                        break;
                    }
                }

                tblModel.addRow(new Object[]{
                        sv.getMaSV(),
                        sv.getHoSV() + " " + sv.getTenSV(),
                        (diemSo >= 0) ? diemSo : ""
                });
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi tải dữ liệu: " + e.getMessage());
        }
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnXemDS;
    private javax.swing.JComboBox<Lop> cboLop;
    private javax.swing.JComboBox<MonHoc> cboMonHoc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanelInput;
    private javax.swing.JPanel jPanelTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDiem;
    private javax.swing.JTextField txtDiem;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtMaSV;
    // End of variables declaration                   
}